sonar.projectKey=theusc6_cloud-platform-engineering
sonar.organization=beacon

# what to exclude from the analysis
# sonar.coverage.exclusions=**/**
sonar.coverage.exclusions=tests/**,docs/**,third_party_libs/**

# metrics to include
sonar.qualitygate.threshold.sqale_rating.warn=5.00
sonar.qualitygate.threshold.sqale_rating.error=8.00

# python version
sonar.python.version=3.11

# complexity
sonar.cognitiveComplexity.threshold=15

# tech debt and code smells
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S125
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.py
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S1481
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.py

# duplicate code
sonar.cpd.exclusions=tests/**,examples/**

# reporting
sonar.verbose=true

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=cloud-platform-engineering
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8