AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stackset to create Systems Manager Distributor Package(s) & State Manager Association(s)'

Parameters:
  PackageName1:
    Type: String
    Description: Required. Provide a name for the first package
    Default: 'XDR'
  S3PackageBucketFolder1:
    Type: String
    Description: Name of the S3 Bucket Folder where the first package manifest is uploaded
    Default: 'xdr'
  Version1:
    Type: String
    Description: Required. Provide the exact version name from the first package manifest file
    Default: '1.0.0'
  AssociationName1:
    Type: String
    Description: Optional. Provide a name for the first Association.
    Default: 'CSD-PackageDistributor-XDR'
  Action1:
    Type: String
    Description: Required. Specify whether to install or uninstall the first package.
    Default: 'Install'
    AllowedValues:
      - 'Install'
      - 'Uninstall'
  InstallationType1:
    Type: String
    Description: Optional. Specify the type of installation for the first package.
    Default: 'Uninstall and reinstall'
    AllowedValues:
      - 'Uninstall and reinstall'
      - 'In-place update'
  CreateLogsBucket:
    Type: String
    Description: 'Indicate whether to create a new S3 logs bucket or use an existing one (true/false)'
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  OutputS3KeyPrefix1:
    Type: String
    Description: The S3 Key Prefix used for AWS Systems Manager Run Command Output for the first package.
    Default: 'xdr'
  ScheduleExpression1:
    Type: String
    Description: 'The Schedule Expression for the AWS Systems Manager Association for the first package. Examples are "rate(30 minutes)", "rate(1 day)", "rate(7 days)"'
    Default: 'cron(0 6 ? * SUN *)'
  TargetResourceTagKey1:
    Type: String
    Description: The AWS Systems Manager Tag Key for the target for the first package.
    Default: 'AutoDeploy'
  TargetResourceTagValue1:
    Type: String
    Description: The AWS Systems Manager Tag Value for the target for the first package.
    Default: 'xdr'

  # The below parameters are going to be implemented at a later date 
  
  # PackageName2:
  #   Type: String
  #   Description: Required. Provide a name for the second package
  #   Default: 'Splunk'
  # S3PackageBucketFolder2:
  #   Type: String
  #   Description: Name of the S3 Bucket Folder where the second package manifest is uploaded
  #   Default: 'splunk'
  # Version2:
  #   Type: String
  #   Description: Required. Provide the exact version name from the second package manifest file
  #   Default: '1.0.0'
  # AssociationName2:
  #   Type: String
  #   Description: Optional. Provide a name for the second Association.
  #   Default: 'CSD-PackageDistributor-Splunk'
  # Action2:
  #   Type: String
  #   Description: Required. Specify whether to install or uninstall the second package.
  #   Default: 'Install'
  #   AllowedValues:
  #     - 'Install'
  #     - 'Uninstall'
  # InstallationType2:
  #   Type: String
  #   Description: Optional. Specify the type of installation for the second package.
  #   Default: 'Uninstall and reinstall'
  #   AllowedValues:
  #     - 'Uninstall and reinstall'
  #     - 'In-place update'
  # OutputS3KeyPrefix2:
  #   Type: String
  #   Description: The S3 Key Prefix used for AWS Systems Manager Run Command Output for the second package.
  #   Default: ''
  # ScheduleExpression2:
  #   Type: String
  #   Description: 'The Schedule Expression for the AWS Systems Manager Association for the second package. Examples are "rate(30 minutes)", "rate(1 day)", "rate(7 days)"'
  #   Default: 'cron(0 6 ? * SUN *)'
  # TargetResourceTagKey2:
  #   Type: String
  #   Description: The AWS Systems Manager Tag Key for the target for the second package.
  #   Default: 'AutoDeploy'
  # TargetResourceTagValue2:
  #   Type: String
  #   Description: The AWS Systems Manager Tag Value for the target for the second package.
  #   Default: 'splunk'

Conditions:
  CreateNewLogsBucket: !Equals [!Ref CreateLogsBucket, 'true']

Resources:
  # This bucket is created via Terraform, but will remain here for future design changes if required as CF template example

  # S3Bucket:
  #   Type: 'AWS::S3::Bucket'
  #   Properties:
  #     BucketName: !Sub "myorg-ssm-package-repo-${AWS::AccountId}-${AWS::Region}"
  #     LoggingConfiguration:
  #       DestinationBucketName: !Sub "myorg-securityhub-s3.9accesslogging-${AWS::AccountId}-${AWS::Region}"
  #       LogFilePrefix: !Sub "myorg-ssm-package-repo-${AWS::AccountId}-${AWS::Region}/"
  #     PublicAccessBlockConfiguration:
  #       BlockPublicAcls: true
  #       BlockPublicPolicy: true
  #       IgnorePublicAcls: true
  #       RestrictPublicBuckets: true
  #     LifecycleConfiguration:
  #         Rules:
  #           -
  #             AbortIncompleteMultipartUpload:
  #               DaysAfterInitiation: 7
  #             Id: "myorg-securityhub-s3.13-default-lifecycle-policy"
  #             Status: "Enabled"
  #             NoncurrentVersionExpirationInDays: 180
  #             NoncurrentVersionTransitions:
  #               -
  #                 TransitionInDays: 30
  #                 StorageClass: GLACIER_IR
  #             Transitions:
  #               -
  #                 TransitionInDays: 0
  #                 StorageClass: INTELLIGENT_TIERING
  #     BucketEncryption:
  #       ServerSideEncryptionConfiguration:
  #         - ServerSideEncryptionByDefault:
  #             SSEAlgorithm: AES256
  #     VersioningConfiguration:
  #       Status: "Enabled"
  #     OwnershipControls:
  #       Rules:
  #         - ObjectOwnership: BucketOwnerEnforced

  # S3BucketPolicy:
  #   Type: 'AWS::S3::BucketPolicy'
  #   Properties:
  #     Bucket: !Ref S3Bucket
  #     PolicyDocument:
  #       Version: '2012-10-17'
  #       Id: 'CompliantDistributorS3BucketPolicy'
  #       Statement:
  #         - Sid: 'HTTPSOnly'
  #           Effect: 'Deny'
  #           Principal: '*'
  #           Action: 's3:*'
  #           Resource:
  #             - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}'
  #             - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}/*'
  #           Condition:
  #             Bool:
  #               aws:SecureTransport: 'false'
  #         - Effect: 'Allow'
  #           Principal: '*'
  #           Action:
  #             - 's3:GetObject'
  #             - 's3:GetBucketLocation'
  #             - 's3:ListBucket'
  #             - 's3:GetObjectVersion'
  #             - 's3:ListBucketVersions'
  #             - 's3:GetObjectTagging'
  #             - 's3:HeadBucket'
  #             - 's3:HeadObject'
  #           Resource:
  #             - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}'
  #             - !Sub 'arn:${AWS::Partition}:s3:::${S3Bucket}/*'
  #           Condition:
  #             StringEquals:
  #               aws:PrincipalOrgID: 'o-3jj2faa76f'

  CreateSSMDistributorPackage1:
    Type: 'Custom::CreateSSMDistributorPackage'
    DependsOn:
      - CreateSSMDistributorPackageExecutePermission
    Properties:
      ServiceToken: !GetAtt 'CreateSSMDistributorLambda.Arn'
      PackageName: !Ref PackageName1
      S3PackageBucket: !Sub "myorg-ssm-package-repo-123456789012-${AWS::Region}"
      S3PackageUrl: !Sub 'https://myorg-ssm-package-repo-123456789012-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/${S3PackageBucketFolder1}'
      S3PackageBucketFolder: !Ref S3PackageBucketFolder1
      Version: !Ref Version1

  # This package is staged for future use with Splunk

  # CreateSSMDistributorPackage2:
  #   Type: 'Custom::CreateSSMDistributorPackage'
  #   DependsOn:
  #     - CreateSSMDistributorPackageExecutePermission
  #   Properties:
  #     ServiceToken: !GetAtt 'CreateSSMDistributorLambda.Arn'
  #     PackageName: !Ref PackageName2
  #     S3PackageBucket: !Ref S3Bucket
  #     S3PackageUrl: !Sub 'https://${S3Bucket}.s3.${AWS::Region}.amazonaws.com/${S3PackageBucketFolder2}'
  #     S3PackageBucketFolder: !Ref S3PackageBucketFolder2
  #     Version: !Ref Version2

  CreateSSMDistributorPackageExecutePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !GetAtt 'CreateSSMDistributorLambda.Arn'
      Principal: 'cloudformation.amazonaws.com'

  CreateSSMDistributorLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      Runtime: python3.11
      MemorySize: 512
      Role: !GetAtt 'CreateSSMDistributorLambdaRole.Arn'
      Timeout: 300
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse
          import logging
          import time

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def handler(event, context):
              response_data = {}
              try:
                  s3 = boto3.client('s3')
                  ssm = boto3.client('ssm')
                  PackageName = event['ResourceProperties']['PackageName']
                  S3PackageBucket = event['ResourceProperties']['S3PackageBucket']
                  S3PackageUrl = event['ResourceProperties']['S3PackageUrl']
                  S3PackageBucketFolder = event['ResourceProperties']['S3PackageBucketFolder']
                  Version = event['ResourceProperties']['Version']

                  logger.info('EVENT Received: {}'.format(event))
                  eventType = event['RequestType']
                  logger.info(f'Event Type: {eventType}')

                  if eventType != 'Delete':
                      manifestFile = S3PackageBucketFolder + "/manifest.json"
                      logger.info(f'Fetching manifest file: {manifestFile} from bucket: {S3PackageBucket}')
                      fileObject = s3.get_object(Bucket=S3PackageBucket, Key=manifestFile)
                      manifestContent = fileObject['Body'].read().decode('utf-8')

                      try:
                          # Try to describe the document to check if it exists
                          describePackage = ssm.describe_document(Name=PackageName)
                          logger.info('Document already exists, updating the document.')
                          
                          # Update the document content and version
                          updatePackage = ssm.update_document(
                              Content=manifestContent,
                              Attachments=[
                                  {
                                      'Key': 'SourceUrl',
                                      'Values': [
                                          S3PackageUrl,
                                      ]
                                  },
                              ],
                              Name=PackageName,
                              DocumentVersion='$LATEST'
                          )
                          updatePackageVersion = ssm.update_document_version(
                              Name=PackageName,
                              DocumentVersion='$LATEST',
                              VersionName=Version
                          )
                          logger.info('Distributor Package Updated: {}'.format(updatePackage))
                      except ssm.exceptions.InvalidDocument as e:
                          logger.info('Document does not exist, creating a new document.')
                          createPackage = ssm.create_document(
                              Content=manifestContent,
                              Attachments=[
                                  {
                                      'Key': 'SourceUrl',
                                      'Values': [
                                          S3PackageUrl,
                                      ]
                                  },
                              ],
                              Name=PackageName,
                              VersionName=Version,
                              DocumentType='Package'
                          )
                          logger.info('Distributor Package Created: {}'.format(createPackage))

                      # Wait for the document to become active
                      for _ in range(10):
                          document_status = ssm.describe_document(Name=PackageName)['Document']['Status']
                          if document_status == 'Active':
                              logger.info(f'Document {PackageName} is now active.')
                              break
                          logger.info(f'Document {PackageName} status: {document_status}. Waiting...')
                          time.sleep(30)  # Wait for 30 seconds before checking again

                      if document_status != 'Active':
                          logger.error(f'Document {PackageName} did not become active within the expected time.')
                          cfnresponse.send(event, context, cfnresponse.FAILED, response_data)
                          return

                      cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
                  else:
                      logger.info('Delete request received')
                      try:
                          deletePackage = ssm.delete_document(Name=PackageName)
                          logger.info('Distributor Package Deleted: {}'.format(deletePackage))
                      except ssm.exceptions.InvalidDocument as e:
                          logger.error('Document does not exist or is already deleted: {}'.format(e))
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
              except Exception as e:
                  logger.error('Exception: {}'.format(e))
                  cfnresponse.send(event, context, cfnresponse.FAILED, response_data)

  CreateSSMDistributorLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub createssmdistributorlambdarole-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowLambdaAssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: CreateSSMDistributorLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutBucketLogging
                  - s3:PutBucketVersioning
                  - s3:GetObject
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource:
                  - !Sub arn:${AWS::Partition}:s3:::myorg-ssm-package-repo-123456789012-${AWS::Region}
                  - !Sub arn:${AWS::Partition}:s3:::myorg-ssm-package-repo-123456789012-${AWS::Region}/*
              - Effect: Allow
                Action:
                  - ssm:CreateDocument
                  - ssm:DescribeDocument
                  - ssm:DeleteDocument
                  - ssm:ListTagsForResource
                  - ssm:PutParameter
                  - ssm:UpdateDocument
                Resource: !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:document/*'
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:CreateLogGroup
                  - logs:PutLogEvents
                Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*'

  OutputS3Bucket:
    Type: 'AWS::S3::Bucket'
    Condition: CreateNewLogsBucket
    Properties:
      BucketName: !Sub "myorg-ssm-package-logs-${AWS::AccountId}-${AWS::Region}"
      LoggingConfiguration:
        DestinationBucketName: !Sub "myorg-securityhub-s3.9accesslogging-${AWS::AccountId}-${AWS::Region}"
        LogFilePrefix: !Sub "myorg-ssm-package-logs-${AWS::AccountId}-${AWS::Region}/"
      LifecycleConfiguration:
        Rules:
          -
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Id: "myorg-securityhub-s3.13-default-lifecycle-policy"
            Status: "Enabled"
            NoncurrentVersionExpirationInDays: 180
            NoncurrentVersionTransitions:
              -
                TransitionInDays: 30
                StorageClass: GLACIER_IR
            Transitions:
              -
                TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: "Enabled"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

  OutputS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Condition: CreateNewLogsBucket
    Properties:
      Bucket: !Ref OutputS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "RequireSSLOnly"
            Effect: "Deny"
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub "arn:${AWS::Partition}:s3:::${OutputS3Bucket}"
              - !Sub "arn:${AWS::Partition}:s3:::${OutputS3Bucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: 'false'

  Association1:
    Type: AWS::SSM::Association
    DependsOn:
      - CreateSSMDistributorPackage1
    Properties:
      AssociationName: !Ref AssociationName1
      Name: AWS-ConfigureAWSPackage
      Parameters:
        action:
          - !Ref Action1
        installationType:
          - !Ref InstallationType1
        name:
          - !Ref PackageName1
      OutputLocation:
        S3Location:
          OutputS3BucketName: !If
            - CreateNewLogsBucket
            - !Ref OutputS3Bucket
            - !Sub "myorg-ssm-package-logs-${AWS::AccountId}-${AWS::Region}"
          OutputS3KeyPrefix: !If
            - CreateNewLogsBucket
            - !Ref OutputS3KeyPrefix1
            - !Ref "OutputS3KeyPrefix1"
      ScheduleExpression: !Ref ScheduleExpression1
      Targets:
        - Key: !Sub 'tag:${TargetResourceTagKey1}'
          Values:
            - !Ref TargetResourceTagValue1

  # This association is staged for the Splunk package

  # Association2:
  #   Type: AWS::SSM::Association
  #   DependsOn:
  #     - CreateSSMDistributorPackage2
  #   Properties:
  #     AssociationName: !Ref AssociationName2
  #     Name: AWS-ConfigureAWSPackage
  #     Parameters:
  #       action:
  #         - !Ref Action2
  #       installationType:
  #         - !Ref InstallationType2
  #       name:
  #         - !Ref PackageName2
  #     OutputLocation:
  #       S3Location:
  #         OutputS3BucketName: !If
  #           - CreateNewLogsBucket
  #           - !Ref OutputS3Bucket
  #           - !Sub "myorg-ssm-package-logs-${AWS::AccountId}-${AWS::Region}"
  #     ScheduleExpression: !Ref ScheduleExpression2
  #     Targets:
  #       - Key: !Sub 'tag:${TargetResourceTagKey2}'
  #         Values:
  #           - !Ref TargetResourceTagValue2
