AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: ExpireObjectsRule
            Status: Enabled
            NoncurrentVersionExpirationInDays: 365
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref BucketName
        LogFilePrefix: logs/
      Tags:
        - Key: Category
          Value: DevSecOps
        - Key: Product
          Value: S3 Bucket

  MyS3BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Statement:
          - Sid: AllowSSLRequestsOnly
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${MyS3Bucket.Arn}/*'
              - !GetAtt MyS3Bucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
            Effect: 'Deny'

Parameters:
  BucketName:
    Type: String
    Description: 'AWS bucket name to create'
    Default: my-secure-bucket
