AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates the Backup IAM role required for the automated centralized backup at scale in AWS Organizations using AWS Backup. It should be deployed in all accounts.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: AWS Backup Configuration
        Parameters:
          - pRegionSelection
          - pTagKey1
          - pTagValue1
    ParameterLabels:
      pRegionSelection:
        default: Region for vault naming
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value

Parameters:
  pTagKey1:
    Type: String
    Default: Category
    Description: This is the tag key to assign to resources.

  pTagValue1:
    Type: String
    Default: Backup
    Description: This is the tag value to assign to resources.

Resources:
  rOrgAccountBackupRole:
    Type: "AWS::IAM::Role"
    Properties:
      Description: Allows AWS Backup to access AWS services
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - backup.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup
        - arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForRestores
        - arn:aws:iam::aws:policy/AWSBackupServiceRolePolicyForS3Backup
        - arn:aws:iam::aws:policy/AWSBackupServiceRolePolicyForS3Restore
      RoleName: !Sub role-myorg-backup-manager
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

Outputs:
  oOrgAccountBackupRole:
    Value: !Ref rOrgAccountBackupRole
    Description: The name of the IAM role created for AWS Backup
