AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys Backup Policies required to manage backups at an organization level. Should be deployed in management account or delegated admin account.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: AWS Backup Configuration
        Parameters:
          - pRegionSelection

    ParameterLabels:
      pRegionSelection:
        default: Region for naming

Parameters:
  pRegionSelection:
    Description: AWS Region for resource naming
    Type: String
    AllowedValues:
      - us-east-1
      - us-east-2
      - us-west-2
      - ap-southeast-1
      - ap-east-1
      - eu-west-2
  
  pOrgbackupAccounts: 
    Description: A CSV list of the AWS accounts or OUs to attach backup policies. 
    Type: CommaDelimitedList
    Default: ""

  pBackupScheduler1:
    Description: The CRON or rate job to initiate backup jobs in sample backup policy 1. For example, cron(0 0/1 ? * * *).
    Type: String
    Default: "cron(0 5/4 ? * * *)"

  pStackBinaryURL:
    Description: The URL for the StackBinary Zip File
    Type: String    
    Default: 'https://awsstorageblogresources.s3.us-west-2.amazonaws.com/ioawssecbackupblog/OrgPolicyCustomResourceManager.zip'


Resources:
  rLocalCacheBucket:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true  
      LifecycleConfiguration:
        Rules:
          -
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 30
            Id: myorg-securityhub-s3.13-default-lifecycle-policy
            Status: Enabled
            NoncurrentVersionExpirationInDays: 180
            NoncurrentVersionTransitions:
              -
                TransitionInDays: 30
                StorageClass: GLACIER_IR
            Transitions:
              -
                TransitionInDays: 0
                StorageClass: INTELLIGENT_TIERING
      LoggingConfiguration:  
        DestinationBucketName: !Sub myorg-securityhub-s3.9accesslogging-${AWS::AccountId}-${AWS::Region}
        LogFilePrefix: !Sub myorg-${AWS::StackName}-${AWS::Region}/

  CacheBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref rLocalCacheBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: RequireSSLOnly
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${rLocalCacheBucket}
              - !Sub arn:aws:s3:::${rLocalCacheBucket}/*
            Condition:
              Bool:
                aws:SecureTransport: false

  CleanupLocalCacheBucketOnDelete:
    Type: Custom::CleanupBucket
    Properties:
      ServiceToken: !GetAtt rGlobalCfnCodeReplicatorLambda.Arn
      S3BucketToCleanup: !Ref rLocalCacheBucket  

  CopySolutionToLocalCacheBucket:
    Type: Custom::ReplicateSolutionBinaries
    Properties:
      ServiceToken: !GetAtt rGlobalCfnCodeReplicatorLambda.Arn
      SolutionDestinationBucket: !Ref rLocalCacheBucket
      SolutionURL: !Ref pStackBinaryURL

  rGlobalCfnCodeReplicatorLambda:
    Type: AWS::Lambda::Function
    Metadata:
        cfn_nag:
          rules_to_suppress:
            - id: W89
              reason: "NA"
            - id: W92
              reason: "NA"    
    Properties:
      Code:
        ZipFile: |-
          #!/usr/bin/env python
          # -*- coding: utf-8 -*-
          import json
          import boto3
          import urllib3
          import os
          import shutil
          from urllib.parse import urlparse
          physical_resource_id = 'GlobalCfnCodeReplicator'  
          def process_bucket_cleanup_request(bucket_name):
              print(f"process_bucket_cleanup_request starting for bucket_name : {bucket_name}")
              s3 = boto3.resource('s3')
              bucket_to_delete = s3.Bucket(bucket_name)
              response = bucket_to_delete.objects.all().delete()
              print(f"process_bucket_cleanup_request all object delete done. Response : {response}")
        
          def download_url(url, save_path):
            c = urllib3.PoolManager()
            with c.request('GET',url, preload_content=False) as resp, open(save_path, 'wb') as out_file:
                shutil.copyfileobj(resp, out_file)
            resp.release_conn()
            
          def lambda_handler(event, context):
            try:
                print(f'Handling event : {event}')
                request_type = event.get('RequestType')              
                solution_url = event['ResourceProperties'].get('SolutionURL')
                solution_bucket = event['ResourceProperties'].get('SolutionDestinationBucket')
                response_data = {
                    'RequestType': request_type,
                    'SolutionURL' : solution_url,
                    'SolutionDestinationBucket' : solution_bucket
                }
                if request_type == 'Create' or request_type == 'Update':
                    if solution_url:
                        print(f'downloading file from : {solution_url}')
                        a = urlparse(solution_url)
                        original_file_name = os.path.basename(a.path)
                        temp_file_name = '/tmp/'+original_file_name
                        download_url(solution_url,temp_file_name)
                        file_size = (os.stat(temp_file_name).st_size / 1024)
                        print(f'Downloaded report to File : {temp_file_name} , Size : {file_size}')
                        s3_client = boto3.client('s3')
                        print(f"uploading payload to : {solution_bucket} at {original_file_name}")
                        extraArgsForUpload = {'ACL':'bucket-owner-full-control', 'Tagging':'Source=StackBinaryURL'}
                        s3_client.upload_file(Filename=temp_file_name, Bucket=solution_bucket, Key=original_file_name,ExtraArgs=extraArgsForUpload)
                elif request_type == 'Delete':
                    solution_bucket = event['ResourceProperties'].get('S3BucketToCleanup')
                    if solution_bucket:
                        process_bucket_cleanup_request(solution_bucket)
                send(event, context, 'SUCCESS', response_data, physical_resource_id)
            except Exception as e:
                send(event, context, 'FAILED', response_data, physical_resource_id)
          def send(event, context, response_status, response_data, physical_resource_id, no_echo=False):
            http = urllib3.PoolManager()
            response_url = event['ResponseURL']
            json_response_body = json.dumps({
                'Status': response_status,
                'Reason': f'See the details in CloudWatch Log Stream: {context.log_stream_name}',
                'PhysicalResourceId': physical_resource_id,
                'StackId': event['StackId'],
                'RequestId': event['RequestId'],
                'LogicalResourceId': event['LogicalResourceId'],
                'NoEcho': no_echo,
                'Data': response_data
            }).encode('utf-8')
            headers = {
                'content-type': '',
                'content-length': str(len(json_response_body))
            }
            try:
                http.request('PUT', response_url,
                             body=json_response_body, headers=headers)
            except Exception as e:
                print(e)
      Description: Copy Solutions Binary to Local Cache Bucket
      Handler: index.lambda_handler
      Role : !GetAtt OrgPolicyCustomResourceManagerRole.Arn
      Runtime: python3.12
      Timeout: 300

  rOrgBackUpPolicy:
    Type: Custom::OrgPolicy
    Properties:
      PolicyPrefix: !Sub "myorg-prod-org-backup-policy"
      PolicyType: BACKUP_POLICY
      PolicyTargets : !Ref pOrgbackupAccounts
      PolicyDescription: >-
        BackupPolicy for Daily Backup as per the resource selection criteria   
      PolicyContents: |-
        [
          {
            "plans": {
              "myorg-prod-backup-plan": {
                "regions": {
                  "@@append": [
                    "us-east-1",
                    "us-east-2",
                    "us-west-2",
                    "ap-southeast-1",
                    "ap-east-1",
                    "eu-west-2"
                  ]
                },
                "rules": {
                  "myorg-prod-backup-rule": {
                    "schedule_expression": { "@@assign": "SCHEDULE_EXPRESSION_PROD" },
                    "start_backup_window_minutes": { "@@assign": "480" },
                    "complete_backup_window_minutes": { "@@assign": "720" },
                    "target_backup_vault_name": { "@@assign": "VAULT_NAME_PROD" },
                    "lifecycle": {
                      "delete_after_days": { "@@assign": "35" }
                    },
                    "recovery_point_tags": {
                      "owner": {
                        "tag_key": { "@@assign": "Owner" },
                        "tag_value": { "@@assign": "Backup" }
                      }
                    },
                    "copy_actions": {
                      "PRIMARY_VAULT_ARN_PROD": {
                        "target_backup_vault_arn": { "@@assign": "PRIMARY_VAULT_ARN_PROD" },
                        "lifecycle": {
                          "delete_after_days": { "@@assign": "35" }
                        }
                      },
                      "SECONDARY_VAULT_ARN_PROD": {
                        "target_backup_vault_arn": { "@@assign": "SECONDARY_VAULT_ARN_PROD" },
                        "lifecycle": {
                          "delete_after_days": { "@@assign": "35" }
                        }
                      }
                    }
                  }
                },
                "backup_plan_tags": {
                  "Category": {
                    "tag_key": { "@@assign": "Category" },
                    "tag_value": { "@@assign": "Backup" }
                  }
                },
                "selections": {
                  "tags": {
                    "myorg-prod-backup-selection": {
                      "iam_role_arn": { "@@assign": "arn:aws:iam::$account:role/BACKUP_ROLE" },
                      "tag_key": { "@@assign": "AWSBackup" },
                      "tag_value": { "@@assign": [ "Production" ] }
                    }
                  }
                }
              }
            }
          }
        ]
    
      Variables:
          - BACKUP_ROLE: !Sub "role-myorg-backup-manager"

          - VAULT_NAME_PROD: !Sub "myorg-prod-mem-backup-vault"
          - PRIMARY_VAULT_ARN_PROD : !Sub "arn:aws:backup:us-west-2:123456789012:backup-vault:myorg-prod-ctr-primary-vault-us-west-2"
          - SECONDARY_VAULT_ARN_PROD : !Sub "arn:aws:backup:ap-southeast-1:123456789012:backup-vault:myorg-prod-ctr-secondary-vault-ap-southeast-1"
          - SCHEDULE_EXPRESSION_PROD : !Ref "pBackupScheduler1"

      ServiceToken: !GetAtt OrgPolicyCustomResourceManager.Arn
      

  OrgPolicyCustomResourceManager:
    Type: AWS::Lambda::Function
    DependsOn: CopySolutionToLocalCacheBucket
    Properties:
      FunctionName: OrgPolicyCustomResourceManager
      Description: Lambda function to deploy CloudFormation custom resources
                   to AWS Organizations.
      Handler: OrgPolicyCustomResourceManager.lambda_handler
      Code:
        S3Bucket: !Ref rLocalCacheBucket
        S3Key: OrgPolicyCustomResourceManager.zip
      Role: !GetAtt OrgPolicyCustomResourceManagerRole.Arn
      Runtime: python3.8
      MemorySize: 256
      Timeout: 300
      Tags:
        - Key: "Category"
          Value: "Backup"

  OrgPolicyCustomResourceManagerRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: IAM role should not allow * resource on its permissions policy
          - id: F3
            reason: IAM role should not allow * resource on its permissions policy
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'lambda.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      Path: '/'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
      - PolicyName: AssumeOrgRole
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Resource:
              - 'arn:aws:iam::*:role/aws-service-role/stacksets.cloudformation.amazonaws.com/AWSServiceRoleForCloudFormationStackSetsOrgAdmin'
              - 'arn:aws:iam::*:role/role-myorg-backup-manager'
      - PolicyName: OrgPermissions
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - organizations:CreatePolicy
              - organizations:DeletePolicy
              - organizations:AttachPolicy
              - organizations:DetachPolicy
              - organizations:ListPolicies
              - organizations:UpdatePolicy
              - organizations:DescribePolicy
              - organizations:ListTargetsForPolicy              
            Resource: '*'
      - PolicyName: S3Permissions
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource: 
              - !Sub arn:aws:s3:::${rLocalCacheBucket}
              - !Sub arn:aws:s3:::${rLocalCacheBucket}/*